### ISSUE TITLE
Ability to set Meta in callbacks

### ISSUE THREAD

**Issue by drush** [nicklandgrebe/caprese#39]
STORY: As a developer I want to be able to set the total number of matching records in the meta section of the JSONAPI response.  When no filter params are set it should show the total number of accessible resources, when the filter is set, it should show the number matching the filtered scope.

Attempted code:
```ruby

class ApiController < Caprese::Controller
  before_action do
    Caprese.config.default_url_options = { host: request.host_with_port }
  end
  
  after_query :set_total
  
  def set_total(resources)
    meta[:total] = resources.size
  end
end

```

ISSUES
* Setting meta in the callback doesn't set it in the response
* resources is nil
* Issue 22 may deprecate after_query altogether.

Looking for some guidance on a better way to set the total, and to get access to the filtered/scoped query before and/or after it executes.

Note: The total is independent of the page size.

**Comment by drush** [comment]
```before_query``` and  ```queried_record_scope``` seems to do the trick

```ruby
  before_query :set_meta_total

  def set_meta_total
    meta[:total] = queried_record_scope.count
  end
```

**Comment by nicklandgrebe** [comment]
Nice, glad you figured this out. I should note that `before_query` is just an alias for the Rails-default `before_action`, which is why I've been meaning to get rid of them. `after_query` has an ill-defined purpose from when I started this and thus it eventually stopped getting called.
