### ISSUE TITLE
Caprese::Controller should inherit from ApplicationController?

### ISSUE THREAD

**Issue by swrobel** [nicklandgrebe/caprese#48]
Thoughts? code ref: https://github.com/nicklandgrebe/caprese/blob/master/lib/caprese/controller.rb#L15

**Comment by nicklandgrebe** [comment]
If you are talking about using `ActionController::API` instead of `Base`, then yes I agree that is an issue to fix

If you are talking about the `ApplicationController` defined within your own application space, this is what comes to mind

```ruby
class Api::V1::ApplicationController < Caprese::Controller
end

class Api::V1::ThingsController < Api::V1::ApplicationController
end
```

I don't understand the question otherwise

**Comment by swrobel** [comment]
I was actually talking about having it inherit from my app's ApplicationController

**Comment by pelletencate** [comment]
I disagree with this idea. 

Every project that I use Caprese in has stuff in the ApplicationController that concerns all of the conventional (i.e. non-api) controllers, but none of my API controllers. If Caprese::Controller would descend from ApplicationController, I would no longer be able to distinguish that in any way, whereas what @swrobel  needs can simply be achieved by using a controller concern included in both your ApplicationController and your APIController.

**Comment by swrobel** [comment]
I agree w/ @pelletencate and ended up going with that solution
